# Generated by Django 4.0.3 on 2022-03-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCreate',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            bases=('movie.movie',),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
